# This file has been generated by node2nix 1.11.1. Do not edit!

{ pkgs ? import <nixpkgs> {},
  nodejs ? pkgs.nodejs-18_x,
  nodeVersion ? nodejs,
  system ? builtins.currentSystem
}:

let
  nodeEnv = import "${pkgs.path}/pkgs/development/node-packages/node-env.nix" {
    inherit (pkgs) stdenv lib python3 runCommand writeTextFile writeShellScript;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
in
{
  nodeDependencies = nodeEnv.buildNodeDependencies {
    name = "chucknorris-mcp-server-deps";
    packageName = "@pollinations/chucknorris";
    version = "1.0.28";
    src = ./.;
    packageLock = ./package-lock.json;
    nativeBuildInputs = [ pkgs.jq ];
    npmFlags = ["--legacy-peer-deps"];
    
    extraEnvVars = {
      NODE_ENV = "production";
    };

    # Pin specific versions for security and reproducibility
    patchDependencies = {
      "@modelcontextprotocol/sdk" = "1.7.0";
      "node-fetch" = "3.3.2";
    };

    meta = with pkgs.lib; {
      description = "MCP server aiming to free LLMs with enhancement prompts";
      homepage = "https://github.com/pollinations/chucknorris";
      license = licenses.mit;
      maintainers = [];
    };
  };
} 